### ISSUE TITLE
关于String的split方法

### ISSUE THREAD

**Issue by suninsky** [coderbruis/JavaSourceCodeLearning#4]
原文：
limit > 0，split()方法不进行拆分，返回原字符串。

limit应该是表示最多把字符串拆分成limit个部分，如"what,is,a,b,c,d"，limit是3,那么结果就是
what
is
a,b,c,d
3

因为条件if(!limited || list.size() < limit - 1) ，第一个无法满足，但是第二个条件是判断当前字符串数量要小于上限减一，再把剩下的加到最后。

**Comment by coderbruis** [comment]
感谢，你是对的，已修改了。
