### ISSUE TITLE
源码

### ISSUE THREAD

**Issue by chenhangege** [coderbruis/JavaSourceCodeLearning#6]

**Comment by xch900910** [comment]
老哥，你你的源码分析就是一个demo，让我们自个debug进行看吗

**Comment by coderbruis** [comment]
项目里的代码只是用作源码分析的demo入口，方便debug进入底层，文章主要是用作记录分析内容以及总结。
 



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "sam_xiong"<notifications@github.com&gt;; 
发送时间: 2021年1月21日(星期四) 下午3:27
收件人: "coderbruis/JavaSourceCodeLearning"<JavaSourceCodeLearning@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [coderbruis/JavaSourceCodeLearning] 源码 (#6)





 
老哥，你你的源码分析就是一个demo，让我们自个debug进行看吗
